//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Gui.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Ficha))]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListarTipoUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAlimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirAlimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarAlimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirAlimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarMedicamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirMedicamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarMedicamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirMedicamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTipoAnimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAnimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirAnimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarAnimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirAnimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarFichaAlimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirFichaAlimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarFichaAlimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirFichaAlimentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Gui.Properties.Settings.Default.Gui_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListarTipoUsuarioCompletedEventHandler ListarTipoUsuarioCompleted;
        
        /// <remarks/>
        public event ListarUsuarioCompletedEventHandler ListarUsuarioCompleted;
        
        /// <remarks/>
        public event InserirUsuarioCompletedEventHandler InserirUsuarioCompleted;
        
        /// <remarks/>
        public event AlterarUsuarioCompletedEventHandler AlterarUsuarioCompleted;
        
        /// <remarks/>
        public event ExcluirUsuarioCompletedEventHandler ExcluirUsuarioCompleted;
        
        /// <remarks/>
        public event ListarAlimentoCompletedEventHandler ListarAlimentoCompleted;
        
        /// <remarks/>
        public event InserirAlimentoCompletedEventHandler InserirAlimentoCompleted;
        
        /// <remarks/>
        public event AlterarAlimentoCompletedEventHandler AlterarAlimentoCompleted;
        
        /// <remarks/>
        public event ExcluirAlimentoCompletedEventHandler ExcluirAlimentoCompleted;
        
        /// <remarks/>
        public event ListarMedicamentoCompletedEventHandler ListarMedicamentoCompleted;
        
        /// <remarks/>
        public event InserirMedicamentoCompletedEventHandler InserirMedicamentoCompleted;
        
        /// <remarks/>
        public event AlterarMedicamentoCompletedEventHandler AlterarMedicamentoCompleted;
        
        /// <remarks/>
        public event ExcluirMedicamentoCompletedEventHandler ExcluirMedicamentoCompleted;
        
        /// <remarks/>
        public event ListarTipoAnimalCompletedEventHandler ListarTipoAnimalCompleted;
        
        /// <remarks/>
        public event ListarAnimalCompletedEventHandler ListarAnimalCompleted;
        
        /// <remarks/>
        public event InserirAnimalCompletedEventHandler InserirAnimalCompleted;
        
        /// <remarks/>
        public event AlterarAnimalCompletedEventHandler AlterarAnimalCompleted;
        
        /// <remarks/>
        public event ExcluirAnimalCompletedEventHandler ExcluirAnimalCompleted;
        
        /// <remarks/>
        public event ListarFichaAlimentoCompletedEventHandler ListarFichaAlimentoCompleted;
        
        /// <remarks/>
        public event InserirFichaAlimentoCompletedEventHandler InserirFichaAlimentoCompleted;
        
        /// <remarks/>
        public event AlterarFichaAlimentoCompletedEventHandler AlterarFichaAlimentoCompleted;
        
        /// <remarks/>
        public event ExcluirFichaAlimentoCompletedEventHandler ExcluirFichaAlimentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarTipoUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
        public TipoUsuario[] ListarTipoUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TipoUsuario tu) {
            object[] results = this.Invoke("ListarTipoUsuario", new object[] {
                        tu});
            return ((TipoUsuario[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarTipoUsuarioAsync(TipoUsuario tu) {
            this.ListarTipoUsuarioAsync(tu, null);
        }
        
        /// <remarks/>
        public void ListarTipoUsuarioAsync(TipoUsuario tu, object userState) {
            if ((this.ListarTipoUsuarioOperationCompleted == null)) {
                this.ListarTipoUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTipoUsuarioOperationCompleted);
            }
            this.InvokeAsync("ListarTipoUsuario", new object[] {
                        tu}, this.ListarTipoUsuarioOperationCompleted, userState);
        }
        
        private void OnListarTipoUsuarioOperationCompleted(object arg) {
            if ((this.ListarTipoUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTipoUsuarioCompleted(this, new ListarTipoUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
        public Usuario[] ListarUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario u) {
            object[] results = this.Invoke("ListarUsuario", new object[] {
                        u});
            return ((Usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarUsuarioAsync(Usuario u) {
            this.ListarUsuarioAsync(u, null);
        }
        
        /// <remarks/>
        public void ListarUsuarioAsync(Usuario u, object userState) {
            if ((this.ListarUsuarioOperationCompleted == null)) {
                this.ListarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarUsuarioOperationCompleted);
            }
            this.InvokeAsync("ListarUsuario", new object[] {
                        u}, this.ListarUsuarioOperationCompleted, userState);
        }
        
        private void OnListarUsuarioOperationCompleted(object arg) {
            if ((this.ListarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarUsuarioCompleted(this, new ListarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario u) {
            this.Invoke("InserirUsuario", new object[] {
                        u});
        }
        
        /// <remarks/>
        public void InserirUsuarioAsync(Usuario u) {
            this.InserirUsuarioAsync(u, null);
        }
        
        /// <remarks/>
        public void InserirUsuarioAsync(Usuario u, object userState) {
            if ((this.InserirUsuarioOperationCompleted == null)) {
                this.InserirUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirUsuarioOperationCompleted);
            }
            this.InvokeAsync("InserirUsuario", new object[] {
                        u}, this.InserirUsuarioOperationCompleted, userState);
        }
        
        private void OnInserirUsuarioOperationCompleted(object arg) {
            if ((this.InserirUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario u) {
            this.Invoke("AlterarUsuario", new object[] {
                        u});
        }
        
        /// <remarks/>
        public void AlterarUsuarioAsync(Usuario u) {
            this.AlterarUsuarioAsync(u, null);
        }
        
        /// <remarks/>
        public void AlterarUsuarioAsync(Usuario u, object userState) {
            if ((this.AlterarUsuarioOperationCompleted == null)) {
                this.AlterarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarUsuarioOperationCompleted);
            }
            this.InvokeAsync("AlterarUsuario", new object[] {
                        u}, this.AlterarUsuarioOperationCompleted, userState);
        }
        
        private void OnAlterarUsuarioOperationCompleted(object arg) {
            if ((this.AlterarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExcluirUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExcluirUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario u) {
            this.Invoke("ExcluirUsuario", new object[] {
                        u});
        }
        
        /// <remarks/>
        public void ExcluirUsuarioAsync(Usuario u) {
            this.ExcluirUsuarioAsync(u, null);
        }
        
        /// <remarks/>
        public void ExcluirUsuarioAsync(Usuario u, object userState) {
            if ((this.ExcluirUsuarioOperationCompleted == null)) {
                this.ExcluirUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirUsuarioOperationCompleted);
            }
            this.InvokeAsync("ExcluirUsuario", new object[] {
                        u}, this.ExcluirUsuarioOperationCompleted, userState);
        }
        
        private void OnExcluirUsuarioOperationCompleted(object arg) {
            if ((this.ExcluirUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarAlimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
        public Alimento[] ListarAlimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Alimento a) {
            object[] results = this.Invoke("ListarAlimento", new object[] {
                        a});
            return ((Alimento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAlimentoAsync(Alimento a) {
            this.ListarAlimentoAsync(a, null);
        }
        
        /// <remarks/>
        public void ListarAlimentoAsync(Alimento a, object userState) {
            if ((this.ListarAlimentoOperationCompleted == null)) {
                this.ListarAlimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAlimentoOperationCompleted);
            }
            this.InvokeAsync("ListarAlimento", new object[] {
                        a}, this.ListarAlimentoOperationCompleted, userState);
        }
        
        private void OnListarAlimentoOperationCompleted(object arg) {
            if ((this.ListarAlimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAlimentoCompleted(this, new ListarAlimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirAlimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirAlimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Alimento a) {
            this.Invoke("InserirAlimento", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void InserirAlimentoAsync(Alimento a) {
            this.InserirAlimentoAsync(a, null);
        }
        
        /// <remarks/>
        public void InserirAlimentoAsync(Alimento a, object userState) {
            if ((this.InserirAlimentoOperationCompleted == null)) {
                this.InserirAlimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirAlimentoOperationCompleted);
            }
            this.InvokeAsync("InserirAlimento", new object[] {
                        a}, this.InserirAlimentoOperationCompleted, userState);
        }
        
        private void OnInserirAlimentoOperationCompleted(object arg) {
            if ((this.InserirAlimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirAlimentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarAlimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarAlimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Alimento a) {
            this.Invoke("AlterarAlimento", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void AlterarAlimentoAsync(Alimento a) {
            this.AlterarAlimentoAsync(a, null);
        }
        
        /// <remarks/>
        public void AlterarAlimentoAsync(Alimento a, object userState) {
            if ((this.AlterarAlimentoOperationCompleted == null)) {
                this.AlterarAlimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarAlimentoOperationCompleted);
            }
            this.InvokeAsync("AlterarAlimento", new object[] {
                        a}, this.AlterarAlimentoOperationCompleted, userState);
        }
        
        private void OnAlterarAlimentoOperationCompleted(object arg) {
            if ((this.AlterarAlimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarAlimentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExcluirAlimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExcluirAlimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Alimento a) {
            this.Invoke("ExcluirAlimento", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void ExcluirAlimentoAsync(Alimento a) {
            this.ExcluirAlimentoAsync(a, null);
        }
        
        /// <remarks/>
        public void ExcluirAlimentoAsync(Alimento a, object userState) {
            if ((this.ExcluirAlimentoOperationCompleted == null)) {
                this.ExcluirAlimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirAlimentoOperationCompleted);
            }
            this.InvokeAsync("ExcluirAlimento", new object[] {
                        a}, this.ExcluirAlimentoOperationCompleted, userState);
        }
        
        private void OnExcluirAlimentoOperationCompleted(object arg) {
            if ((this.ExcluirAlimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirAlimentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarMedicamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
        public Medicamento[] ListarMedicamento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Medicamento m) {
            object[] results = this.Invoke("ListarMedicamento", new object[] {
                        m});
            return ((Medicamento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarMedicamentoAsync(Medicamento m) {
            this.ListarMedicamentoAsync(m, null);
        }
        
        /// <remarks/>
        public void ListarMedicamentoAsync(Medicamento m, object userState) {
            if ((this.ListarMedicamentoOperationCompleted == null)) {
                this.ListarMedicamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarMedicamentoOperationCompleted);
            }
            this.InvokeAsync("ListarMedicamento", new object[] {
                        m}, this.ListarMedicamentoOperationCompleted, userState);
        }
        
        private void OnListarMedicamentoOperationCompleted(object arg) {
            if ((this.ListarMedicamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarMedicamentoCompleted(this, new ListarMedicamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirMedicamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirMedicamento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Medicamento m) {
            this.Invoke("InserirMedicamento", new object[] {
                        m});
        }
        
        /// <remarks/>
        public void InserirMedicamentoAsync(Medicamento m) {
            this.InserirMedicamentoAsync(m, null);
        }
        
        /// <remarks/>
        public void InserirMedicamentoAsync(Medicamento m, object userState) {
            if ((this.InserirMedicamentoOperationCompleted == null)) {
                this.InserirMedicamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirMedicamentoOperationCompleted);
            }
            this.InvokeAsync("InserirMedicamento", new object[] {
                        m}, this.InserirMedicamentoOperationCompleted, userState);
        }
        
        private void OnInserirMedicamentoOperationCompleted(object arg) {
            if ((this.InserirMedicamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirMedicamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarMedicamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarMedicamento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Medicamento m) {
            this.Invoke("AlterarMedicamento", new object[] {
                        m});
        }
        
        /// <remarks/>
        public void AlterarMedicamentoAsync(Medicamento m) {
            this.AlterarMedicamentoAsync(m, null);
        }
        
        /// <remarks/>
        public void AlterarMedicamentoAsync(Medicamento m, object userState) {
            if ((this.AlterarMedicamentoOperationCompleted == null)) {
                this.AlterarMedicamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarMedicamentoOperationCompleted);
            }
            this.InvokeAsync("AlterarMedicamento", new object[] {
                        m}, this.AlterarMedicamentoOperationCompleted, userState);
        }
        
        private void OnAlterarMedicamentoOperationCompleted(object arg) {
            if ((this.AlterarMedicamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarMedicamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExcluirMedicamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExcluirMedicamento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Medicamento m) {
            this.Invoke("ExcluirMedicamento", new object[] {
                        m});
        }
        
        /// <remarks/>
        public void ExcluirMedicamentoAsync(Medicamento m) {
            this.ExcluirMedicamentoAsync(m, null);
        }
        
        /// <remarks/>
        public void ExcluirMedicamentoAsync(Medicamento m, object userState) {
            if ((this.ExcluirMedicamentoOperationCompleted == null)) {
                this.ExcluirMedicamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirMedicamentoOperationCompleted);
            }
            this.InvokeAsync("ExcluirMedicamento", new object[] {
                        m}, this.ExcluirMedicamentoOperationCompleted, userState);
        }
        
        private void OnExcluirMedicamentoOperationCompleted(object arg) {
            if ((this.ExcluirMedicamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirMedicamentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarTipoAnimal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
        public TipoAnimal[] ListarTipoAnimal([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TipoAnimal ta) {
            object[] results = this.Invoke("ListarTipoAnimal", new object[] {
                        ta});
            return ((TipoAnimal[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarTipoAnimalAsync(TipoAnimal ta) {
            this.ListarTipoAnimalAsync(ta, null);
        }
        
        /// <remarks/>
        public void ListarTipoAnimalAsync(TipoAnimal ta, object userState) {
            if ((this.ListarTipoAnimalOperationCompleted == null)) {
                this.ListarTipoAnimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTipoAnimalOperationCompleted);
            }
            this.InvokeAsync("ListarTipoAnimal", new object[] {
                        ta}, this.ListarTipoAnimalOperationCompleted, userState);
        }
        
        private void OnListarTipoAnimalOperationCompleted(object arg) {
            if ((this.ListarTipoAnimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTipoAnimalCompleted(this, new ListarTipoAnimalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarAnimal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
        public Animal[] ListarAnimal([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Animal a) {
            object[] results = this.Invoke("ListarAnimal", new object[] {
                        a});
            return ((Animal[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAnimalAsync(Animal a) {
            this.ListarAnimalAsync(a, null);
        }
        
        /// <remarks/>
        public void ListarAnimalAsync(Animal a, object userState) {
            if ((this.ListarAnimalOperationCompleted == null)) {
                this.ListarAnimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAnimalOperationCompleted);
            }
            this.InvokeAsync("ListarAnimal", new object[] {
                        a}, this.ListarAnimalOperationCompleted, userState);
        }
        
        private void OnListarAnimalOperationCompleted(object arg) {
            if ((this.ListarAnimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAnimalCompleted(this, new ListarAnimalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirAnimal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirAnimal([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Animal a) {
            this.Invoke("InserirAnimal", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void InserirAnimalAsync(Animal a) {
            this.InserirAnimalAsync(a, null);
        }
        
        /// <remarks/>
        public void InserirAnimalAsync(Animal a, object userState) {
            if ((this.InserirAnimalOperationCompleted == null)) {
                this.InserirAnimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirAnimalOperationCompleted);
            }
            this.InvokeAsync("InserirAnimal", new object[] {
                        a}, this.InserirAnimalOperationCompleted, userState);
        }
        
        private void OnInserirAnimalOperationCompleted(object arg) {
            if ((this.InserirAnimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirAnimalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarAnimal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarAnimal([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Animal a) {
            this.Invoke("AlterarAnimal", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void AlterarAnimalAsync(Animal a) {
            this.AlterarAnimalAsync(a, null);
        }
        
        /// <remarks/>
        public void AlterarAnimalAsync(Animal a, object userState) {
            if ((this.AlterarAnimalOperationCompleted == null)) {
                this.AlterarAnimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarAnimalOperationCompleted);
            }
            this.InvokeAsync("AlterarAnimal", new object[] {
                        a}, this.AlterarAnimalOperationCompleted, userState);
        }
        
        private void OnAlterarAnimalOperationCompleted(object arg) {
            if ((this.AlterarAnimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarAnimalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExcluirAnimal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExcluirAnimal([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Animal a) {
            this.Invoke("ExcluirAnimal", new object[] {
                        a});
        }
        
        /// <remarks/>
        public void ExcluirAnimalAsync(Animal a) {
            this.ExcluirAnimalAsync(a, null);
        }
        
        /// <remarks/>
        public void ExcluirAnimalAsync(Animal a, object userState) {
            if ((this.ExcluirAnimalOperationCompleted == null)) {
                this.ExcluirAnimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirAnimalOperationCompleted);
            }
            this.InvokeAsync("ExcluirAnimal", new object[] {
                        a}, this.ExcluirAnimalOperationCompleted, userState);
        }
        
        private void OnExcluirAnimalOperationCompleted(object arg) {
            if ((this.ExcluirAnimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirAnimalCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarFichaAlimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
        public FichaAlimento[] ListarFichaAlimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] FichaAlimento fa) {
            object[] results = this.Invoke("ListarFichaAlimento", new object[] {
                        fa});
            return ((FichaAlimento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarFichaAlimentoAsync(FichaAlimento fa) {
            this.ListarFichaAlimentoAsync(fa, null);
        }
        
        /// <remarks/>
        public void ListarFichaAlimentoAsync(FichaAlimento fa, object userState) {
            if ((this.ListarFichaAlimentoOperationCompleted == null)) {
                this.ListarFichaAlimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarFichaAlimentoOperationCompleted);
            }
            this.InvokeAsync("ListarFichaAlimento", new object[] {
                        fa}, this.ListarFichaAlimentoOperationCompleted, userState);
        }
        
        private void OnListarFichaAlimentoOperationCompleted(object arg) {
            if ((this.ListarFichaAlimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarFichaAlimentoCompleted(this, new ListarFichaAlimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirFichaAlimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirFichaAlimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] FichaAlimento fa) {
            this.Invoke("InserirFichaAlimento", new object[] {
                        fa});
        }
        
        /// <remarks/>
        public void InserirFichaAlimentoAsync(FichaAlimento fa) {
            this.InserirFichaAlimentoAsync(fa, null);
        }
        
        /// <remarks/>
        public void InserirFichaAlimentoAsync(FichaAlimento fa, object userState) {
            if ((this.InserirFichaAlimentoOperationCompleted == null)) {
                this.InserirFichaAlimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirFichaAlimentoOperationCompleted);
            }
            this.InvokeAsync("InserirFichaAlimento", new object[] {
                        fa}, this.InserirFichaAlimentoOperationCompleted, userState);
        }
        
        private void OnInserirFichaAlimentoOperationCompleted(object arg) {
            if ((this.InserirFichaAlimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirFichaAlimentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarFichaAlimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarFichaAlimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] FichaAlimento fa) {
            this.Invoke("AlterarFichaAlimento", new object[] {
                        fa});
        }
        
        /// <remarks/>
        public void AlterarFichaAlimentoAsync(FichaAlimento fa) {
            this.AlterarFichaAlimentoAsync(fa, null);
        }
        
        /// <remarks/>
        public void AlterarFichaAlimentoAsync(FichaAlimento fa, object userState) {
            if ((this.AlterarFichaAlimentoOperationCompleted == null)) {
                this.AlterarFichaAlimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarFichaAlimentoOperationCompleted);
            }
            this.InvokeAsync("AlterarFichaAlimento", new object[] {
                        fa}, this.AlterarFichaAlimentoOperationCompleted, userState);
        }
        
        private void OnAlterarFichaAlimentoOperationCompleted(object arg) {
            if ((this.AlterarFichaAlimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarFichaAlimentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExcluirFichaAlimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExcluirFichaAlimento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] FichaAlimento fa) {
            this.Invoke("ExcluirFichaAlimento", new object[] {
                        fa});
        }
        
        /// <remarks/>
        public void ExcluirFichaAlimentoAsync(FichaAlimento fa) {
            this.ExcluirFichaAlimentoAsync(fa, null);
        }
        
        /// <remarks/>
        public void ExcluirFichaAlimentoAsync(FichaAlimento fa, object userState) {
            if ((this.ExcluirFichaAlimentoOperationCompleted == null)) {
                this.ExcluirFichaAlimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirFichaAlimentoOperationCompleted);
            }
            this.InvokeAsync("ExcluirFichaAlimento", new object[] {
                        fa}, this.ExcluirFichaAlimentoOperationCompleted, userState);
        }
        
        private void OnExcluirFichaAlimentoOperationCompleted(object arg) {
            if ((this.ExcluirFichaAlimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirFichaAlimentoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
    public partial class TipoUsuario {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descricaoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FichaAlimento))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
    public partial class Ficha {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string dataCriacaoField;
        
        private string dataValidadeField;
        
        private string descricaoField;
        
        private Animal animalField;
        
        private Usuario usuarioField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataCriacao {
            get {
                return this.dataCriacaoField;
            }
            set {
                this.dataCriacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataValidade {
            get {
                return this.dataValidadeField;
            }
            set {
                this.dataValidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Animal animal {
            get {
                return this.animalField;
            }
            set {
                this.animalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
    public partial class Animal {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string corField;
        
        private byte[] fotoField;
        
        private string nomeField;
        
        private double pesoField;
        
        private bool pesoFieldSpecified;
        
        private string porteField;
        
        private TipoAnimal tipoAnimalField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cor {
            get {
                return this.corField;
            }
            set {
                this.corField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] Foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public double Peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PesoSpecified {
            get {
                return this.pesoFieldSpecified;
            }
            set {
                this.pesoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Porte {
            get {
                return this.porteField;
            }
            set {
                this.porteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TipoAnimal tipoAnimal {
            get {
                return this.tipoAnimalField;
            }
            set {
                this.tipoAnimalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
    public partial class TipoAnimal {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descricaoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
    public partial class Usuario {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string cpfField;
        
        private string crmvField;
        
        private string loginField;
        
        private string nomeField;
        
        private string senhaField;
        
        private TipoUsuario tipousuarioField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Crmv {
            get {
                return this.crmvField;
            }
            set {
                this.crmvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TipoUsuario tipousuario {
            get {
                return this.tipousuarioField;
            }
            set {
                this.tipousuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
    public partial class FichaAlimento : Ficha {
        
        private double qtd_max_calField;
        
        private bool qtd_max_calFieldSpecified;
        
        private Alimento[] listaAlimentoField;
        
        /// <remarks/>
        public double Qtd_max_cal {
            get {
                return this.qtd_max_calField;
            }
            set {
                this.qtd_max_calField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qtd_max_calSpecified {
            get {
                return this.qtd_max_calFieldSpecified;
            }
            set {
                this.qtd_max_calFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Alimento[] listaAlimento {
            get {
                return this.listaAlimentoField;
            }
            set {
                this.listaAlimentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
    public partial class Alimento {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string dataReposicaoField;
        
        private string nomeField;
        
        private double quantidadeField;
        
        private bool quantidadeFieldSpecified;
        
        private double valorCaloricoField;
        
        private bool valorCaloricoFieldSpecified;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataReposicao {
            get {
                return this.dataReposicaoField;
            }
            set {
                this.dataReposicaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public double Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantidadeSpecified {
            get {
                return this.quantidadeFieldSpecified;
            }
            set {
                this.quantidadeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double ValorCalorico {
            get {
                return this.valorCaloricoField;
            }
            set {
                this.valorCaloricoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorCaloricoSpecified {
            get {
                return this.valorCaloricoFieldSpecified;
            }
            set {
                this.valorCaloricoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.basica")]
    public partial class Medicamento {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string dataReposicaoField;
        
        private string nomeField;
        
        private int quantidadeField;
        
        private bool quantidadeFieldSpecified;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataReposicao {
            get {
                return this.dataReposicaoField;
            }
            set {
                this.dataReposicaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantidadeSpecified {
            get {
                return this.quantidadeFieldSpecified;
            }
            set {
                this.quantidadeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarTipoUsuarioCompletedEventHandler(object sender, ListarTipoUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTipoUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTipoUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TipoUsuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoUsuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarUsuarioCompletedEventHandler(object sender, ListarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InserirUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AlterarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ExcluirUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarAlimentoCompletedEventHandler(object sender, ListarAlimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAlimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAlimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Alimento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Alimento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InserirAlimentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AlterarAlimentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ExcluirAlimentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarMedicamentoCompletedEventHandler(object sender, ListarMedicamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarMedicamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarMedicamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Medicamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Medicamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InserirMedicamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AlterarMedicamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ExcluirMedicamentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarTipoAnimalCompletedEventHandler(object sender, ListarTipoAnimalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTipoAnimalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTipoAnimalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TipoAnimal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoAnimal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarAnimalCompletedEventHandler(object sender, ListarAnimalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAnimalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAnimalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Animal[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Animal[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InserirAnimalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AlterarAnimalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ExcluirAnimalCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarFichaAlimentoCompletedEventHandler(object sender, ListarFichaAlimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarFichaAlimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarFichaAlimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FichaAlimento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FichaAlimento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InserirFichaAlimentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AlterarFichaAlimentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ExcluirFichaAlimentoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591